version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.firebase:firebase-crashlytics
    versions:
    - 17.4.0
    - 17.4.1
